# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 129d0133eae936ffe29450422fc01ca9dcb58d63aa52539c12f98cdd5ee04cec7aa4b65a0ea13abcfad1ceccb42e0ab6ac2b0eb5af4c2d685011c268e1319ed2

test:
  secret_key_base: 74abbc80661c4ea02f02d1c4fbfc966111c7d50a63b56113887b8b672c4f7a9ccfd3c6a29b0ec6e7b5d3bfa4fe7c4615a39a658c09022bd7e412bb471e907482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
